/* Autogenerated file. Do not edit manually. */

import { TableId } from "@latticexyz/utils";
import { defineComponent, Type as RecsType, World } from "@latticexyz/recs";

export function defineContractComponents(world: World) {
  return {
    ID: (() => {
      const tableId = new TableId("", "ID");
      return defineComponent(
        world,
        {
          cartridges: RecsType.BigInt,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
    Cartridge: (() => {
      const tableId = new TableId("", "Cartridge");
      return defineComponent(
        world,
        {
          author: RecsType.String,
          parent: RecsType.BigInt,
          staticRoot: RecsType.String,
          dynRoot: RecsType.String,
        },
        {
          metadata: {
            contractId: tableId.toHexString(),
            tableId: tableId.toString(),
          },
        }
      );
    })(),
  };
}
