// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { ID, IDTableId } from "./tables/ID.sol";
import { Cartridge, CartridgeData, CartridgeTableId } from "./tables/Cartridge.sol";
