// SPDX-License-Identifier: MIT
pragma solidity >=0.8.0;

/* Autogenerated file. Do not edit manually. */

import { Action } from "./../../libraries/CartridgeLib.sol";

interface ICartridgeSystem {
  function createCartridge(bytes32 staticRoot, bytes32 dynRoot) external;

  function playCartridge(uint256 id, Action[] memory activity) external;
}
